name = "lead-proxy"
main = "workers/lead-proxy/worker.js"
compatibility_date = "2024-10-01"

[vars]
ALLOWED_ORIGIN = "https://www.empireautom.org"

routes = [
  { pattern = "www.empireautom.org/api/lead", zone_name = "empireautom.org" }
]
